# permissions for end users to edit updaters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: updater-editor-role
rules:
- apiGroups:
  - manifest-updater.koyuta.io.koyuta.io
  resources:
  - updaters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manifest-updater.koyuta.io.koyuta.io
  resources:
  - updaters/status
  verbs:
  - get
