# permissions for end users to view updaters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: updater-viewer-role
rules:
- apiGroups:
  - manifest-updater.koyuta.io.koyuta.io
  resources:
  - updaters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - manifest-updater.koyuta.io.koyuta.io
  resources:
  - updaters/status
  verbs:
  - get
