apiVersion: manifest-updater.koyuta.io/v1alpha1
kind: Updater
metadata:
  name: example-updater
spec:
  registry:
    dockerHub: index.docker.io/example/app
    filter: dev-.*
  repository:
    git: git@github.com:koyuta/manifests
    base: master
    head: feature/update-tag
    path: /overlay/prd
